export const VALIDATION_LIMITS = {
  DISCOUNT: {
    MAX_PERCENTAGE: 100,
    MAX_AMOUNT: 100000,
    MIN_VALUE: 0,
  },
  PRODUCT: {
    MAX_STOCK: 9999,
    MIN_STOCK: 0,
    MIN_VALUE: 0,
  },
  CART: {
    MIN_TOTAL_FOR_PERCENTAGE_COUPON: 10000,
    BULK_PURCHASE_THRESHOLD: 10,
    BULK_PURCHASE_BONUS: 0.05,
    MAX_DISCOUNT_RATE: 0.5,
    DEFAULT_QUANTITY: 1,
  },
} as const;
